version: "3.8"
services: 
    sqldata:
        container_name: sql-data
        image: mcr.microsoft.com/mssql/server:2019-latest

    library:
        container_name: libraryapi
        image: ${DOCKER_REGISTRY-}libraryapi
        build:
            context: .
            dockerfile: ./src/Library.Api/Dockerfile  